name: Linda Souza
favicon: null
layout_spectrum: 0.47757191909477115
typography_spectrum: 0.8517180860508233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5544133018702269
  lightness: 0.29786341451108456
  saturation: 0.4161998596973717
  rhythmicContrast: 0.14505514060147107
purpose: []
